In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

import vents_np
import polaires_np
import isochrone_np as iso
import env_concave_np as env
import fonctions_utiles_np as f

In [2]:
%matplotlib qt

In [ ]:
VENT = vents_np.V1


POLAIRE = polaires_np.P2
POLAIRE_V = polaires_np.Vector_vect

In [4]:
I = iso.isopoint_np(p = [0, 0, 0, 0], t = 0, dt = 0.25, n = 80, V = VENT, P = POLAIRE_V)

In [5]:
print(I)

[[ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 4.40858164e-02  7.19415139e-02  1.00000000e+00  0.00000000e+00]
 [ 1.98377523e-01  2.73043236e-01  1.00000000e+00  0.00000000e+00]
 [ 3.73432628e-01  4.37233430e-01  1.00000000e+00  0.00000000e+00]
 [ 4.86135912e-01  4.86135912e-01  1.00000000e+00  0.00000000e+00]
 [ 6.08324772e-01  5.19558439e-01  1.00000000e+00  0.00000000e+00]
 [ 7.11260774e-01  5.16761201e-01  1.00000000e+00  0.00000000e+00]
 [ 8.13560823e-01  4.98550714e-01  1.00000000e+00  0.00000000e+00]
 [ 8.89150261e-01  4.53044686e-01  1.00000000e+00  0.00000000e

In [6]:
plt.scatter(I[:, 0], I[:, 1])
plt.axis('equal')

(np.float64(-1.1916666666666669),
 np.float64(1.1916666666666669),
 np.float64(-0.5828245121176135),
 np.float64(0.5720528648918499))

In [7]:
N = iso.nuageinfo_np(I = I, t = 0, dt = 0.25, n = 80, V = VENT, P = POLAIRE_V)

In [8]:
plt.scatter(N[:, 0], N[:, 1])
plt.axis('equal')

(np.float64(-2.3833333333333337),
 np.float64(2.3833333333333337),
 np.float64(-1.165649024235227),
 np.float64(1.1441057297836998))

In [9]:
# nuages = [N]
# enveloppes = [I]
# for k in range(5):
#     E = env.enveloppe_np(N, 0.5)
#     enveloppes.append(E)
#     N = iso.nuageinfo_np(I = E, t = 0, dt = 0.25, n = 80, V = VENT, P = POLAIRE_V)
#     nuages.append(N)


In [10]:
# i = 5
# plt.scatter(nuages[i][:, 0], nuages[i][:, 1])
# plt.plot(enveloppes[i][:, 0], enveloppes[i][:, 1], color='red')
# plt.axis('equal')

In [11]:
I_s = iso.isosuivante_np(I = I, t = 0, dt = 0.25, n = 80, V = VENT, P = POLAIRE)

In [12]:
print(I_s)

[[-2.26374135e+00 -2.77228360e-16  2.00000000e+00  6.00000000e+01]
 [-2.26040180e+00  8.49973537e-02  2.00000000e+00  6.10000000e+01]
 [-2.25313541e+00  1.77325602e-01  2.00000000e+00  6.10000000e+01]
 [-2.24313733e+00  2.61798919e-01  2.00000000e+00  6.20000000e+01]
 [-2.22151708e+00  3.51853740e-01  2.00000000e+00  6.20000000e+01]
 [-2.19074173e+00  4.31877802e-01  2.00000000e+00  6.30000000e+01]
 [-2.15529999e+00  5.17441746e-01  2.00000000e+00  6.30000000e+01]
 [-2.11468898e+00  5.92414858e-01  2.00000000e+00  6.40000000e+01]
 [-2.06629843e+00  6.71381057e-01  2.00000000e+00  6.40000000e+01]
 [-2.01562798e+00  7.39562360e-01  2.00000000e+00  6.50000000e+01]
 [-1.95548016e+00  8.09986405e-01  2.00000000e+00  6.50000000e+01]
 [-1.89669153e+00  8.70381944e-01  2.00000000e+00  6.60000000e+01]
 [-1.82626748e+00  9.30529761e-01  2.00000000e+00  6.60000000e+01]
 [-1.74730128e+00  9.78920310e-01  2.00000000e+00  6.60000000e+01]
 [-1.67171185e+00  1.02442634e+00  2.00000000e+00  6.70000000e

In [13]:
plt.scatter(I[:, 0], I[:, 1])
plt.scatter(I_s[:, 0], I_s[:, 1])
plt.axis('equal')

(np.float64(-2.490115489614977),
 np.float64(2.490115489614977),
 np.float64(-1.2320489235917687),
 np.float64(1.2212772763660051))

In [25]:
I_n = iso.niso_np(p = [0.0, 0.0, 0.0, 0.0], t = 0, N = 24, dt = 0.25, n = 80, V = VENT, P = POLAIRE_V)

nombre isochrones : 3, temps écoulé : 0.25 heures, nombre de points : 95
nombre isochrones : 4, temps écoulé : 0.50 heures, nombre de points : 121
nombre isochrones : 5, temps écoulé : 0.75 heures, nombre de points : 150
nombre isochrones : 6, temps écoulé : 1.00 heures, nombre de points : 181
nombre isochrones : 7, temps écoulé : 1.25 heures, nombre de points : 213
nombre isochrones : 8, temps écoulé : 1.50 heures, nombre de points : 248
nombre isochrones : 9, temps écoulé : 1.75 heures, nombre de points : 246
nombre isochrones : 10, temps écoulé : 2.00 heures, nombre de points : 281
nombre isochrones : 11, temps écoulé : 2.25 heures, nombre de points : 306
nombre isochrones : 12, temps écoulé : 2.50 heures, nombre de points : 332
nombre isochrones : 13, temps écoulé : 2.75 heures, nombre de points : 347
nombre isochrones : 14, temps écoulé : 3.00 heures, nombre de points : 369
nombre isochrones : 15, temps écoulé : 3.25 heures, nombre de points : 397
nombre isochrones : 16, temps éco

Pour N = 19 : 20s P2 et 23s Vect

Pour N = 24 : 40s P2 et 43s Vect

Pour N = 19 :           11s Vect (avec kdTree)

Pour N = 24 :           22s Vect (avec kdTree)

Pour N = 19 :           2.1s Vect (avec kdTree + vectorisation bouclage)

Pour N = 24 :           3.4s Vect (avec kdTree + vectorisation bouclage)

In [15]:
plt.scatter(I_n[:, 0], I_n[:, 1])
plt.axis('equal')

(np.float64(-38.13333333333333),
 np.float64(38.13333333333333),
 np.float64(-18.650384387763644),
 np.float64(18.305691676539197))

In [16]:
I_t, route = iso.toutesiso_np(p_dep = [0, 0, 0, 0] , p_arr = [0, -17], t = 0, dt = 0.25, n = 80, V = VENT, P = POLAIRE_V, e_arr = 1)

nombre isochrones : 3, temps écoulé : 0.25 heures, nombre de points : 95
nombre isochrones : 4, temps écoulé : 0.50 heures, nombre de points : 121
nombre isochrones : 5, temps écoulé : 0.75 heures, nombre de points : 150
nombre isochrones : 6, temps écoulé : 1.00 heures, nombre de points : 181
nombre isochrones : 7, temps écoulé : 1.25 heures, nombre de points : 213
nombre isochrones : 8, temps écoulé : 1.50 heures, nombre de points : 248
nombre isochrones : 9, temps écoulé : 1.75 heures, nombre de points : 246
nombre isochrones : 10, temps écoulé : 2.00 heures, nombre de points : 281
nombre isochrones : 11, temps écoulé : 2.25 heures, nombre de points : 306
nombre isochrones : 12, temps écoulé : 2.50 heures, nombre de points : 332
nombre isochrones : 13, temps écoulé : 2.75 heures, nombre de points : 347
nombre isochrones : 14, temps écoulé : 3.00 heures, nombre de points : 369
nombre isochrones : 15, temps écoulé : 3.25 heures, nombre de points : 397
nombre isochrones : 16, temps éco

In [17]:
plt.scatter(I_t[:, 0], I_t[:, 1])
plt.plot(route[..., 0], route[..., 1], c = 'red')
plt.axis('equal')

(np.float64(-38.13333333333333),
 np.float64(38.13333333333333),
 np.float64(-18.650384387763644),
 np.float64(18.305691676539197))

In [18]:
print(route)

[[-1.31452574e-01 -1.64262404e+01  3.10000000e+01  6.51000000e+02]
 [-6.61782660e-01 -1.58959103e+01  3.00000000e+01  6.25000000e+02]
 [-1.19211275e+00 -1.53655803e+01  2.90000000e+01  5.91000000e+02]
 [-1.72244283e+00 -1.48352502e+01  2.80000000e+01  5.76000000e+02]
 [-2.25277292e+00 -1.43049201e+01  2.70000000e+01  5.52000000e+02]
 [-1.72244283e+00 -1.37745900e+01  2.60000000e+01  5.26000000e+02]
 [-1.19211275e+00 -1.32442599e+01  2.50000000e+01  5.05000000e+02]
 [-1.72244283e+00 -1.27139298e+01  2.40000000e+01  4.88000000e+02]
 [-2.25277292e+00 -1.21835997e+01  2.30000000e+01  4.69000000e+02]
 [-2.78310300e+00 -1.16532697e+01  2.20000000e+01  4.39000000e+02]
 [-2.25277292e+00 -1.11229396e+01  2.10000000e+01  4.15000000e+02]
 [-1.72244283e+00 -1.05926095e+01  2.00000000e+01  3.73000000e+02]
 [-1.19211275e+00 -1.00622794e+01  1.90000000e+01  4.22000000e+02]
 [-1.72244283e+00 -9.53194931e+00  1.80000000e+01  3.31000000e+02]
 [-2.25277292e+00 -9.00161922e+00  1.70000000e+01  3.04000000e

In [19]:
import cProfile, pstats
cProfile.run("iso.niso_np(p = [0.0, 0.0, 0.0, 0.0], t = 0, N = 10, dt = 0.25, n = 80, V = VENT, P = POLAIRE_V)", "prof")
stats = pstats.Stats("prof")
stats.sort_stats("tottime")   # ← change ici (ex: 'time', 'calls', ...)
stats.print_stats()


nombre isochrones : 3, temps écoulé : 0.25 heures, nombre de points : 95
nombre isochrones : 4, temps écoulé : 0.50 heures, nombre de points : 121
nombre isochrones : 5, temps écoulé : 0.75 heures, nombre de points : 150
nombre isochrones : 6, temps écoulé : 1.00 heures, nombre de points : 181
nombre isochrones : 7, temps écoulé : 1.25 heures, nombre de points : 213
nombre isochrones : 8, temps écoulé : 1.50 heures, nombre de points : 248
nombre isochrones : 9, temps écoulé : 1.75 heures, nombre de points : 246
nombre isochrones : 10, temps écoulé : 2.00 heures, nombre de points : 281
Sat Nov 29 14:52:09 2025    prof

         280928 function calls (280900 primitive calls) in 0.382 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    18155    0.110    0.000    0.110    0.000 {built-in method numpy.array}
     3368    0.064    0.000    0.082    0.000 /Users/louisbouscasse/Desktop/routage numpy/env_concave_np.py:75(segments_in